from django.urls import path

from .views.analysis import (
    analyze_primer_view,
    analyze_primerpair_view,
    analyze_sequence_view,
    download_product_sequence,
    save_generated_primerpair,
)
from .views.auth import register
from .views.cloning import (
    cloning_asset_list,
    cloning_construct_create,
    cloning_construct_delete,
    cloning_construct_detail,
    cloning_construct_download_genbank,
    cloning_construct_list,
)
from .views.home import home
from .views.primerpairs import (
    download_selected_primerpairs,
    primerpair_combined_create,
    primerpair_create,
    primerpair_delete,
    primerpair_list,
    primerpair_products,
    primerpair_products_async,
    primerpair_products_save,
)
from .views.primers import (
    delete_selected_primers,
    download_selected_primers,
    primer_create,
    primer_delete,
    primer_import_excel,
    primer_list,
)
from .views.projects import (
    project_add_pcr_product,
    project_add_primerpair,
    project_add_sequencefile,
    project_create,
    project_dashboard,
    project_download_sequence_files,
    project_list,
    project_primer_list,
    project_remove_pcr_product,
    project_remove_primerpair,
    project_remove_sequencefile,
)
from .views.sequence_files import (
    pcrproduct_delete,
    pcrproduct_detail,
    pcrproduct_list,
    primer_binding_analysis,
    primer_binding_analysis_async,
    primer_binding_status,
    sequencefile_circular_view,
    sequencefile_linear_create_primer,
    sequencefile_linear_delete_primer,
    sequencefile_linear_record_data,
    sequencefile_linear_save_pcr_product,
    sequencefile_linear_view,
    sequencefile_list,
    sequencefile_update_type,
    sequencefile_upload,
)

urlpatterns = [
    path("", home, name="home"),
    path("register/", register, name="register"),
    path("projects/", project_list, name="project_list"),
    path("projects/create/", project_create, name="project_create"),
    path("projects/<int:project_id>/", project_dashboard, name="project_dashboard"),
    path("projects/<int:project_id>/primers/", project_primer_list, name="project_primer_list"),
    path(
        "projects/<int:project_id>/sequence-files/download/",
        project_download_sequence_files,
        name="project_download_sequence_files",
    ),
    path("projects/<int:project_id>/add-pair/<int:pair_id>/", project_add_primerpair, name="project_add_primerpair"),
    path("projects/<int:project_id>/remove-pair/<int:pair_id>/", project_remove_primerpair, name="project_remove_primerpair"),
    path(
        "projects/<int:project_id>/add-sequence-file/<int:sequencefile_id>/",
        project_add_sequencefile,
        name="project_add_sequencefile",
    ),
    path(
        "projects/<int:project_id>/remove-sequence-file/<int:sequencefile_id>/",
        project_remove_sequencefile,
        name="project_remove_sequencefile",
    ),
    path(
        "projects/<int:project_id>/add-pcr-product/<int:pcr_product_id>/",
        project_add_pcr_product,
        name="project_add_pcr_product",
    ),
    path(
        "projects/<int:project_id>/remove-pcr-product/<int:pcr_product_id>/",
        project_remove_pcr_product,
        name="project_remove_pcr_product",
    ),
    path("cloning/assets/", cloning_asset_list, name="cloning_asset_list"),
    path("cloning/constructs/", cloning_construct_list, name="cloning_construct_list"),
    path("cloning/constructs/create/", cloning_construct_create, name="cloning_construct_create"),
    path("cloning/constructs/<int:construct_id>/", cloning_construct_detail, name="cloning_construct_detail"),
    path("cloning/constructs/<int:construct_id>/delete/", cloning_construct_delete, name="cloning_construct_delete"),
    path(
        "cloning/constructs/<int:construct_id>/download/genbank/",
        cloning_construct_download_genbank,
        name="cloning_construct_download_genbank",
    ),
    path("primers/", primer_list, name="primer_list"),
    path("primers/create/", primer_create, name="primer_create"),
    path("primers/import/", primer_import_excel, name="primer_import_excel"),
    path("primers/download/", download_selected_primers, name="download_selected_primers"),
    path("primers/delete/", delete_selected_primers, name="delete_selected_primers"),
    path("primers/<int:primer_id>/delete/", primer_delete, name="primer_delete"),
    path("primerpairs/", primerpair_list, name="primerpair_list"),
    path("primerpairs/create/", primerpair_create, name="primerpair_create"),
    path("primerpairs/create/combined/", primerpair_combined_create, name="primerpair_combined_create"),
    path("primerpairs/<int:primerpair_id>/delete/", primerpair_delete, name="primerpair_delete"),
    path("primerpairs/download/", download_selected_primerpairs, name="download_selected_primerpairs"),
    path("primerpairs/products/", primerpair_products, name="primerpair_products"),
    path("primerpairs/products/async/", primerpair_products_async, name="primerpair_products_async"),
    path("primerpairs/products/save/", primerpair_products_save, name="primerpair_products_save"),
    path("analyze-sequence/", analyze_sequence_view, name="analyze_sequence"),
    path("save-primerpair/", save_generated_primerpair, name="save_generated_primerpair"),
    path("primer-product/download/", download_product_sequence, name="download_product_sequence"),
    path("sequence-files/", sequencefile_list, name="sequencefile_list"),
    path("sequence-files/upload/", sequencefile_upload, name="sequencefile_upload"),
    path(
        "sequence-files/<int:sequencefile_id>/update-type/",
        sequencefile_update_type,
        name="sequencefile_update_type",
    ),
    path("pcr-products/", pcrproduct_list, name="pcrproduct_list"),
    path("pcr-products/<int:pcrproduct_id>/", pcrproduct_detail, name="pcrproduct_detail"),
    path("pcr-products/<int:pcrproduct_id>/delete/", pcrproduct_delete, name="pcrproduct_delete"),
    path("sequence-files/<int:sequencefile_id>/linear-view/", sequencefile_linear_view, name="sequencefile_linear_view"),
    path("sequence-files/<int:sequencefile_id>/circular-view/", sequencefile_circular_view, name="sequencefile_circular_view"),
    path(
        "sequence-files/<int:sequencefile_id>/linear-view/record-data/",
        sequencefile_linear_record_data,
        name="sequencefile_linear_record_data",
    ),
    path(
        "sequence-files/<int:sequencefile_id>/linear-view/create-primer/",
        sequencefile_linear_create_primer,
        name="sequencefile_linear_create_primer",
    ),
    path(
        "sequence-files/<int:sequencefile_id>/linear-view/save-pcr-product/",
        sequencefile_linear_save_pcr_product,
        name="sequencefile_linear_save_pcr_product",
    ),
    path(
        "sequence-files/<int:sequencefile_id>/linear-view/delete-primer/",
        sequencefile_linear_delete_primer,
        name="sequencefile_linear_delete_primer",
    ),
    path("analyze-primer/", analyze_primer_view, name="analyze_primer"),
    path("analyze-primerpair/", analyze_primerpair_view, name="analyze_primerpair"),
    path("primer-binding/", primer_binding_analysis, name="primer_binding"),
    path("primer-binding/async/", primer_binding_analysis_async, name="primer_binding_async"),
    path("analysis-jobs/<str:task_id>/", primer_binding_status, name="primer_binding_status"),

    # Legacy aliases kept for compatibility.
    path("primer_list", primer_list),
    path("create/", primer_create),
    path("delete/<int:primer_id>/", primer_delete),
    path("primerpair_list", primerpair_list),
    path("primerpair_create/", primerpair_create),
    path("project_list", project_list),
    path("analyze_sequence/", analyze_sequence_view),
    path("save_primerpair/", save_generated_primerpair),
]
